### ISSUE TITLE
Elm shouldn't be used for animation. Performance of this app is slow on my Macbook Pro.

### ISSUE THREAD

**Issue by trusktr** [Dobiasd/Breakout#1] opened 2016-01-03 06:57 UTC
Check out my reasoning here: https://github.com/elm-lang/elm-compiler/issues/1247

**Comment by Dobiasd** [comment] 2016-01-03 08:21
Thanks for reporting.

I'm aware that Elm currently is not the best solution for web games. Breakout was mainly an exercise for ne in learning functional programming. A real game, meant to play, should run smoothly, I totally agree.
Manual CSS Manipulation from within the elm code, would perhaps be a solution, but is not was I was aiming for. Also at the time of writing `elm-html` was not even there. ;)

What I experienced was not that the frame rate for games in Elm (Breakout for example) is generally low, but that only every nth frame takes an abnormal amount of this. In Firefox the problem is much worse than in Chrome. Some time ago there were some discussions regarding this problem on the mailing list.

topic 1: https://groups.google.com/forum/#!topic/elm-discuss/j3v7a_75oPI

topic 2: https://groups.google.com/forum/#!topic/elm-discuss/ErEx6IZNNAQ

The gist at this time was, that the problem comes from the garbadge collector, and the problem (only every nth frame is slow, not every single frame). The problem was also reproducible in pure JS without using Elm at all.
One possible solution was a [package, that Jason Merrill wrote](https://github.com/jwmerrill/elm-animation-frame). He also did the main part of the amazing analysis, that lead to the garbadge collector issue.

Can you tell me if the performance problem with Breakout at your PC occurs every single frame or only every nth frame like in the discussions?
If it is the second case, we can try to use `elm-animation-frame` to see if this helps.

**Comment by trusktr** [comment] 2016-01-03 08:44
Interesting, thanks for pointing those discussions out! Indeed I've seen this problem before with the garabage collection. Yes, I was seeing breakout pause approximately every Nth frame. But, with that being said, the animations that are in breakout are simple enough that GC should really impact it.

I'm guessing a big chunk of things being GCed are Elm infrastructure data that run each tick. There's plenty of complex WebGL demos on threejs.org that don't stutter, probably because there isn't much data to collect. I'm betting your actual game data isn't a source of high GC compared to the stuff Elm is probably doing.

No matter what we do, just having an infrastructure like Elm's running on each tick is simply going to be overkill for animations. Here's a bunch of breakouts, non of which stutter at all: 
- http://www.jsbreakouts.org
- http://breakout.enclavegames.com/lesson10.html
- http://kodogames.com/game/breakout

**Comment by Dobiasd** [comment] 2016-01-03 09:57
I [made](https://gist.github.com/Dobiasd/f3ed7ed9c94cfff17a05) a version of Breakout using `AnimationFrame.frame` instead of `Time.FPS`. It would be nice if you could try it out and let me know if it works better on your machine compared to the [default version](http://daiw.de/games/breakout/): http://daiw.de/share/elm/breakout_AnimationFrame/

But of course you are right. It should be possible to make such a simple game run smoothly in an easy way. The examples you posted show clearly that it is possible.
Up to now, I unfortunately do not really understand what Elm is doing each tick in the background. You seem to have more knowledge about it. Do you have an idea on how the overhead / garbage to collect in the runtime could be reduced? Could you perhaps even create a branch or a PR with a cure?

I guess Evan is putting his focus more on Elm for web apps and not as much for games right now. But if you could help out, I'm pretty sure it would be much appreciated.

**Comment by trusktr** [comment] 2016-01-03 22:13
The AnimationFrame version is doesn't stutter! Nice!

**Comment by Dobiasd** [comment] 2016-01-04 07:22
Great! I just [committed](https://github.com/Dobiasd/Breakout/commit/4364edeaf2b0e2b8e00362c7fbe37e93026442f0) it. Thank you very much for your help.

**Closed as completed by Dobiasd** 2016-01-04 07:22 UTC
